services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: domain_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"  
    command: --default-authentication-plugin=mysql_native_password  
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    restart: on-failure

volumes:
  Db_data:
